#!/usr/bin/env python3
"""Generate cypha_rest_static_embed.hpp from tools/static/* for CYPHA_EMBED_STATIC_UI."""
from __future__ import annotations

import argparse
from pathlib import Path


def c_raw_string(body: str, tag: str) -> str:
    """Return a C++11 raw string literal, picking a delimiter that does not appear in body."""
    for n in range(10):
        delim = f"cypha_ui_{tag}_{n}"
        if f"){delim}" not in body:
            return f'R"{delim}({body}){delim}"'
    raise RuntimeError(f"could not find raw-string delimiter for {tag}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--static-dir", type=Path, required=True)
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args()

    files = [
        ("index.html", "text/html; charset=utf-8"),
        ("app.js", "application/javascript; charset=utf-8"),
    ]

    parts: list[str] = [
        "// Generated by native/scripts/embed_static_ui.py — do not edit.",
        "#pragma once",
        "#include <string>",
        "#include <unordered_map>",
        "",
        "namespace cypha_rest_ui {",
        "",
        "inline const std::unordered_map<std::string, std::pair<const char*, const char*>>& embedded_files() {",
        "  static const std::unordered_map<std::string, std::pair<const char*, const char*>> kFiles = {",
    ]

    for fname, mime in files:
        path = args.static_dir / fname
        text = path.read_text(encoding="utf-8")
        lit = c_raw_string(text, fname.replace(".", "_"))
        parts.append(f'    {{"/ui/{fname}", {{{lit}, "{mime}"}}},')

    parts.extend(
        [
            "  };",
            "  return kFiles;",
            "}",
            "",
            "}  // namespace cypha_rest_ui",
            "",
        ]
    )

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(parts), encoding="utf-8")


if __name__ == "__main__":
    main()
