# Generate cypha_rest_static_embed.hpp from tools/static/* for CYPHA_EMBED_STATIC_UI.
param(
    [Parameter(Mandatory = $true)]
    [string]$StaticDir,
    [Parameter(Mandatory = $true)]
    [string]$Out
)

$ErrorActionPreference = "Stop"

function Get-RawStringLiteral {
    param([string]$Body, [string]$Tag)
    for ($n = 0; $n -lt 10; $n++) {
        $delim = "cypha_ui_${Tag}_$n"
        if ($Body -notmatch [regex]::Escape(")$delim")) {
            return "R`"$delim($Body)$delim`""
        }
    }
    throw "could not find raw-string delimiter for $Tag"
}

$files = @(
    @{ Name = "index.html"; Mime = "text/html; charset=utf-8" },
    @{ Name = "app.js"; Mime = "application/javascript; charset=utf-8" }
)

$lines = New-Object System.Collections.Generic.List[string]
[void]$lines.Add("// Generated by native/scripts/embed_static_ui.ps1 — do not edit.")
[void]$lines.Add("#pragma once")
[void]$lines.Add("#include <string>")
[void]$lines.Add("#include <unordered_map>")
[void]$lines.Add("")
[void]$lines.Add("namespace cypha_rest_ui {")
[void]$lines.Add("")
[void]$lines.Add("inline const std::unordered_map<std::string, std::pair<const char*, const char*>>& embedded_files() {")
[void]$lines.Add("  static const std::unordered_map<std::string, std::pair<const char*, const char*>> kFiles = {")

foreach ($f in $files) {
    $path = Join-Path $StaticDir $f.Name
    if (-not (Test-Path $path)) { throw "Missing static file: $path" }
    $text = [System.IO.File]::ReadAllText($path)
    $tag = ($f.Name -replace '\.', '_')
    $lit = Get-RawStringLiteral -Body $text -Tag $tag
    [void]$lines.Add("    {`"/ui/$($f.Name)`", {$lit, `"$($f.Mime)`"}},")
}

[void]$lines.Add("  };")
[void]$lines.Add("  return kFiles;")
[void]$lines.Add("}")
[void]$lines.Add("")
[void]$lines.Add("}  // namespace cypha_rest_ui")
[void]$lines.Add("")

$outDir = Split-Path -Parent $Out
if ($outDir -and -not (Test-Path $outDir)) {
    New-Item -ItemType Directory -Path $outDir -Force | Out-Null
}
[System.IO.File]::WriteAllText($Out, ($lines -join "`n"))
