// Generate cypha_rest_static_embed.hpp from tools/static/* (no Python required).
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

namespace fs = std::filesystem;

namespace {

std::string c_raw_string(const std::string& body, const std::string& tag) {
  for (int n = 0; n < 10; ++n) {
    const std::string delim = "cypha_ui_" + tag + "_" + std::to_string(n);
    if (body.find(")" + delim) == std::string::npos) {
      return "R\"" + delim + "(" + body + ")" + delim + "\"";
    }
  }
  throw std::runtime_error("could not find raw-string delimiter for " + tag);
}

std::string read_file(const fs::path& path) {
  std::ifstream in(path, std::ios::binary);
  if (!in) {
    throw std::runtime_error("cannot read " + path.string());
  }
  std::ostringstream buf;
  buf << in.rdbuf();
  return buf.str();
}

}  // namespace

int main(int argc, char** argv) {
  if (argc != 5 || std::string(argv[1]) != "--static-dir" || std::string(argv[3]) != "--out") {
    std::fprintf(stderr, "usage: embed_static_ui --static-dir DIR --out HEADER.hpp\n");
    return 2;
  }

  try {
    const fs::path static_dir = argv[2];
    const fs::path out_path = argv[4];

    const struct {
      const char* name;
      const char* mime;
    } files[] = {
        {"index.html", "text/html; charset=utf-8"},
        {"app.js", "application/javascript; charset=utf-8"},
    };

    std::ostringstream out;
    out << "// Generated by native/tools/embed_static_ui.cpp — do not edit.\n"
        << "#pragma once\n"
        << "#include <string>\n"
        << "#include <unordered_map>\n"
        << "\n"
        << "namespace cypha_rest_ui {\n"
        << "\n"
        << "inline const std::unordered_map<std::string, std::pair<const char*, const char*>>& "
           "embedded_files() {\n"
        << "  static const std::unordered_map<std::string, std::pair<const char*, const char*>> "
           "kFiles = {\n";

    for (const auto& f : files) {
      const std::string text = read_file(static_dir / f.name);
      std::string tag = f.name;
      for (char& c : tag) {
        if (c == '.') {
          c = '_';
        }
      }
      const std::string lit = c_raw_string(text, tag);
      out << "    {\"/ui/" << f.name << "\", {" << lit << ", \"" << f.mime << "\"}},\n";
    }

    out << "  };\n"
        << "  return kFiles;\n"
        << "}\n"
        << "\n"
        << "}  // namespace cypha_rest_ui\n"
        << "\n";

    fs::create_directories(out_path.parent_path());
    std::ofstream f(out_path, std::ios::binary);
    if (!f) {
      throw std::runtime_error("cannot write " + out_path.string());
    }
    const std::string payload = out.str();
    f.write(payload.data(), static_cast<std::streamsize>(payload.size()));
    return 0;
  } catch (const std::exception& e) {
    std::fprintf(stderr, "embed_static_ui: %s\n", e.what());
    return 1;
  }
}
